Preparing packaging

diff --git a/do-release b/do-release
--- a/do-release
+++ b/do-release
@@ -42,44 +42,44 @@ echo "You are about to build and publish version $NEXT_VERSION"
 read -sn 1 -p "Press any key to continue..."
 echo
 
+if [ ! -d "./venv" ]; then
+    virtualenv venv
+fi
+
 # Make sure we are in sync with remote
 git checkout -q master && git fetch -q && git pull -q
 
 # Verify that there is nothing to commit
-if [ $(git_is_dirty) -eq 1 ]; then
-    git status
-    echo
-    echo -e " [error] Hey dumbass, commit your shit.. Abort !\n\n"
-   #exit 1
-fi
+#if [ $(git_is_dirty) -eq 1 ]; then
+#    git status
+#    echo
+#    echo -e " [error] Hey dumbass, commit your shit.. Abort !\n\n"
+#   #exit 1
+#fi
+#
+## Verify that there is no untracked files
+#if [ $(git_has_untracked_files) -gt 0 ]; then
+#    git status
+#    echo
+#    echo -e " [error] I see untracked files, you dirty bastard.. Abort !\n\n"
+#    exit 1
+#fi
 
-# Verify that there is no untracked files
-if [ $(git_has_untracked_files) -gt 0 ]; then
-    git status
-    echo
-    echo -e " [error] I see untracked files, you dirty bastard.. Abort !\n\n"
-    exit 1
-fi
-
-echo " [info] Bumping version"
-sed -i -e "s/    version='"$CURRENT_VERSION"',/    version='"$NEXT_VERSION"',/" setup.py
-git commit -aqm "Version bump: $CURRENT_VERSION -> $NEXT_VERSION @wip"
-git push -q
-
-echo " [info] Creating tag v$NEXT_VERSION"
-git tag -s "v$NEXT_VERSION" -m "Release $NEXT_VERSION"
-git push --tags origin "v$NEXT_VERSION"
-
-echo " [info] Updating changelog"
-if [ ! -d "./venv" ]; then
-    virtualenv venv
-fi
-./venv/bin/pip install -q gitchangelog
-./venv/bin/gitchangelog > CHANGELOG
-rm -rf venv
-git add CHANGELOG
-git commit -qm "Updated CHANGELOG @wip"
-git push -q
+#echo " [info] Bumping version"
+#sed -i -e "s/    version='"$CURRENT_VERSION"',/    version='"$NEXT_VERSION"',/" setup.py
+#git commit -aqm "Version bump: $CURRENT_VERSION -> $NEXT_VERSION @wip"
+#git push -q
+#
+#echo " [info] Creating tag v$NEXT_VERSION"
+#git tag -s "v$NEXT_VERSION" -m "Release $NEXT_VERSION"
+#git push --tags origin "v$NEXT_VERSION"
+#
+#echo " [info] Updating changelog"
+#./venv/bin/pip install -q gitchangelog
+#./venv/bin/gitchangelog > CHANGELOG
+#git add CHANGELOG
+#git commit -qm "Updated CHANGELOG @wip"
+#git push -q
 
 # check if a git branch exists for the current major_minor release (ex: release_1_0)
 if [ `git branch --list $BRANCH` ]; then # if not, create one.
@@ -94,8 +94,13 @@ git push -q --set-upstream origin $BRANCH > /dev/null
 git checkout -q master
 
 echo " [info] Pushing to PyPi"
-python setup.py sdist build upload
+./venv/bin/pip install -q wheel
+./venv/bin/python setup.py sdist
+./venv/bin/python setup.py bdist_wheel --universal
+./venv/bin/twine upload dist/*
+
 
 echo " [done] Published release v$NEXT_VERSION"
 echo
+rm -rf venv
 exit 0
